image: docker:latest  #1

variables:  #2
  DOCKER_DRIVER: overlay2
#  DOCKER_HOST: tcp://192.168.209.154:80  # docker host，本地可不写,
  TAG: root/hello-spring:v0.1  # 生成的镜像名称
cache:  #3
  paths:
    - .m2/repository
services:  #4
  - docker:dind
stages:  #5
  - package
  - deploy
maven-package:  #6
  image: maven:3.5-jdk-8-alpine
  tags:
    - SHARE_MAVEN_JDK
  stage: package
  script:
    - mvn clean package -Dmaven.test.skip=true
  artifacts:
    paths:
      - target/*.jar
build-master:  #7
  tags:
    - SHARE_MAVEN_JDK
  stage: deploy
  script:
    - docker login 192.168.209.154:80 -u admin -p Harbor12345
    - docker build -t $TAG . # 根据Dockerfile文件构建镜像
    - docker rm -f test || true # 删除测试容器
    - docker run -d --name test -p 5000:5000 $TAG # 运行容器，$TAG是开头设置的变量，表示的是镜像
  only:
    - master